"""migrate absensipegawaiandadmin

Revision ID: 2223d970001a
Revises: 
Create Date: 2025-02-18 19:39:13.730932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2223d970001a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('jam_lembur', sa.Time(), nullable=True))
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_pegawai', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('jam_lembur')
        batch_op.drop_column('admin_id')

    # ### end Alembic commands ###
