"""tambah kolom nomor pegawai

Revision ID: 55941ed92a0e
Revises: 2223d970001a
Create Date: 2025-02-24 15:19:28.595548

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55941ed92a0e'
down_revision = '2223d970001a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('absensi_pegawai', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])

    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nomor_pegawai', sa.String(length=50), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.drop_column('nomor_pegawai')

    with op.batch_alter_table('absensi_pegawai', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
