"""create lama_kerja table

Revision ID: 697e598ac956
Revises: 55941ed92a0e
Create Date: 2025-04-27 21:31:51.999899

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '697e598ac956'
down_revision = '55941ed92a0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lama_kerja',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('pegawai_id', sa.Integer(), nullable=True),
    sa.Column('tanggal', sa.Date(), nullable=True),
    sa.Column('nama_pegawai', sa.String(length=100), nullable=True),
    sa.Column('divisi', sa.String(length=100), nullable=True),
    sa.Column('lama_terdeteksi', sa.Integer(), nullable=True),
    sa.Column('area_cctv', sa.String(length=100), nullable=True),
    sa.Column('foto_bukti', sa.LargeBinary(), nullable=True),
    sa.ForeignKeyConstraint(['admin_id'], ['admin.id'], ),
    sa.ForeignKeyConstraint(['pegawai_id'], ['pegawai.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lama_kerja')
    # ### end Alembic commands ###
