"""Tambah kolom folder_path ke tabel Pegawai

Revision ID: 7e97aed09831
Revises: e30b5566da84
Create Date: 2025-06-16 12:44:08.704485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e97aed09831'
down_revision = 'e30b5566da84'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('folder_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.drop_column('folder_path')

    # ### end Alembic commands ###
