"""add description column to Folder

Revision ID: b7982fd77d66
Revises: 7e97aed09831
Create Date: 2025-06-17 14:12:07.005706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7982fd77d66'
down_revision = '7e97aed09831'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('superadmin', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('pegawai', schema=None) as batch_op:
        batch_op.drop_column('photo')

    with op.batch_alter_table('admin', schema=None) as batch_op:
        batch_op.drop_column('photo')

    # ### end Alembic commands ###
